apiVersion: v1
kind: Pod
metadata:
  name: clearsessions-manual
spec:
  restartPolicy: Never
  containers:
  - name: cleanup
    image: django-test:latest
    imagePullPolicy: IfNotPresent
    command: ["python", "manage.py", "clearsessions"]
    env:
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: django-secrets
          key: database-url
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: django-secrets
          key: secret-key